const languages = [
  "Afrikaans - Afrikaans",
  "Albanian - Shqip",
  "Amharic - አማርኛ",
  "Arabic - العربية",
  "Armenian - Հայերեն",
  "Azerbaijani - Azərbaycanca",
  "Basque - Euskara",
  "Belarusian - Беларуская",
  "Bengali - বাংলা",
  "Bosnian - Bosanski",
  "Bulgarian - Български",
  "Burmese - မြန်မာစာ",
  "Catalan - Català",
  "Cebuano - Cebuano",
  "Chinese - 中文",
  "Corsican - Corsu",
  "Croatian - Hrvatski",
  "Czech - Čeština",
  "Danish - Dansk",
  "Dutch - Nederlands",
  "English - English",
  "Esperanto - Esperanto",
  "Estonian - Eesti",
  "Farsi (Persian) - فارسی",
  "Finnish - Suomi",
  "French - Français",
  "Frisian - Frysk",
  "Galician - Galego",
  "Georgian - ქართული",
  "German - Deutsch",
  "Greek - Ελληνικά",
  "Gujarati - ગુજરાતી",
  "Haitian Creole - Kreyòl Ayisyen",
  "Hausa - Hausa",
  "Hawaiian - ʻŌlelo Hawaiʻi",
  "Hebrew - עברית",
  "Hindi - हिंदी",
  "Hmong - Hmoob",
  "Hungarian - Magyar",
  "Icelandic - Íslenska",
  "Igbo - Igbo",
  "Indonesian - Bahasa Indonesia",
  "Irish - Gaeilge",
  "Italian - Italiano",
  "Japanese - 日本語",
  "Javanese - Basa Jawa",
  "Kannada - ಕನ್ನಡ",
  "Kazakh - Қазақ",
  "Khmer - ខ្មែរ",
  "Kinyarwanda - Ikinyarwanda",
  "Korean - 한국어",
  "Kurdish - Kurdî",
  "Kyrgyz - Кыргызча",
  "Lao - ລາວ",
  "Latin - Latina",
  "Latvian - Latviešu",
  "Lithuanian - Lietuvių",
  "Luxembourgish - Lëtzebuergesch",
  "Macedonian - Македонски",
  "Malagasy - Malagasy",
  "Malay - Bahasa Melayu",
  "Malayalam - മലയാളം",
  "Maltese - Malti",
  "Maori - Te Reo Māori",
  "Marathi - मराठी",
  "Mongolian - Монгол",
  "Nepali - नेपाली",
  "Norwegian - Norsk",
  "Pashto - پښتو",
  "Polish - Polski",
  "Portuguese - Português",
  "Punjabi - ਪੰਜਾਬੀ",
  "Romanian - Română",
  "Russian - Русский",
  "Samoan - Gagana Sāmoa",
  "Scots Gaelic - Gàidhlig",
  "Serbian - Српски",
  "Shona - chiShona",
  "Sindhi - سنڌي",
  "Sinhala - සිංහල",
  "Slovak - Slovenčina",
  "Slovenian - Slovenščina",
  "Somali - Soomaali",
  "Spanish - Español",
  "Sundanese - Basa Sunda",
  "Swahili - Kiswahili",
  "Swedish - Svenska",
  "Tagalog - Tagalog",
  "Tajik - Тоҷикӣ",
  "Tamil - தமிழ்",
  "Tatar - Татарча",
  "Telugu - తెలుగు",
  "Thai - ไทย",
  "Turkish - Türkçe",
  "Turkmen - Türkmen",
  "Ukrainian - Українська",
  "Urdu - اردو",
  "Uyghur - ئۇيغۇرچە",
  "Uzbek - Oʻzbek",
  "Vietnamese - Tiếng Việt",
  "Welsh - Cymraeg",
  "Xhosa - isiXhosa",
  "Yiddish - ייִדיש",
  "Yoruba - Yorùbá",
  "Zulu - isiZulu",
];

export default languages;
